class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        dict1 = {}
        for x in s: 
            try: 
                dict1[x] += 1
            except: 
                dict1[x] = 1
        dict2 = {}
        for x in t: 
            try: 
                dict2[x] += 1
            except: 
                dict2[x] = 1
        for x in dict1.keys(): 
            try: 
                if dict2[x] != dict1[x]: 
                    return x
            except:  
                    return x
        for x in dict2.keys(): 
            try: 
                if dict2[x] != dict1[x]: 
                    return x
            except:  
                    return x
        
            
                


#https://leetcode.com/problems/find-the-difference/
#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.